# the name by which the project can be referenced within Serena
project_name: 'aionui'

# list of languages for which language servers are started; choose from:
#   al                  bash                clojure             cpp                 csharp
#   csharp_omnisharp    dart                elixir              elm                 erlang
#   fortran             fsharp              go                  groovy              haskell
#   java                julia               kotlin              lua                 markdown
#   matlab              nix                 pascal              perl                php
#   powershell          python              python_jedi         r                   rego
#   ruby                ruby_solargraph     rust                scala               swift
#   terraform           toml                typescript          typescript_vts      vue
#   yaml                zig
#   (This list may be outdated. For the current list, see values of Language enum here:
#   https://github.com/oraios/serena/blob/main/src/solidlsp/ls_config.py
#   For some languages, there are alternative language servers, e.g. csharp_omnisharp, ruby_solargraph.)
# Note:
#   - For C, use cpp
#   - For JavaScript, use typescript
#   - For Free Pascal/Lazarus, use pascal
# Special requirements:
#   Some languages require additional setup/installations.
#   See here for details: https://oraios.github.io/serena/01-about/020_programming-languages.html#language-servers
# When using multiple languages, the first language server that supports a given file will be used for that file.
# The first language is the default language and the respective language server will be used as a fallback.
# Note that when using the JetBrains backend, language servers are not used and this list is correspondingly ignored.
languages:
  - typescript
  - python

# the encoding used by text files in the project
# For a list of possible encodings, see https://docs.python.org/3.11/library/codecs.html#standard-encodings
encoding: 'utf-8'

# whether to use project's .gitignore files to ignore files
ignore_all_files_in_gitignore: true

# list of additional paths to ignore in all projects
# same syntax as gitignore, so you can use * and **
ignored_paths:
  - .drift/
  - .local_docs/
  - .scratchpad/

# whether the project is in read-only mode
# If set to true, all editing tools will be disabled and attempts to use them will result in an error
# Added on 2025-04-18
read_only: false

# list of tool names to exclude. We recommend not excluding any tools, see the readme for more details.
# Below is the complete list of tools for convenience.
# To make sure you have the latest list of tools, and to view their descriptions,
# execute `uv run scripts/print_tool_overview.py`.
#
#  * `activate_project`: Activates a project by name.
#  * `check_onboarding_performed`: Checks whether project onboarding was already performed.
#  * `create_text_file`: Creates/overwrites a file in the project directory.
#  * `delete_lines`: Deletes a range of lines within a file.
#  * `delete_memory`: Deletes a memory from Serena's project-specific memory store.
#  * `execute_shell_command`: Executes a shell command.
#  * `find_referencing_code_snippets`: Finds code snippets in which the symbol at the given location is referenced.
#  * `find_referencing_symbols`: Finds symbols that reference the symbol at the given location (optionally filtered by type).
#  * `find_symbol`: Performs a global (or local) search for symbols with/containing a given name/substring (optionally filtered by type).
#  * `get_current_config`: Prints the current configuration of the agent, including the active and available projects, tools, contexts, and modes.
#  * `get_symbols_overview`: Gets an overview of the top-level symbols defined in a given file.
#  * `initial_instructions`: Gets the initial instructions for the current project.
#     Should only be used in settings where the system prompt cannot be set,
#     e.g. in clients you have no control over, like Claude Desktop.
#  * `insert_after_symbol`: Inserts content after the end of the definition of a given symbol.
#  * `insert_at_line`: Inserts content at a given line in a file.
#  * `insert_before_symbol`: Inserts content before the beginning of the definition of a given symbol.
#  * `list_dir`: Lists files and directories in the given directory (optionally with recursion).
#  * `list_memories`: Lists memories in Serena's project-specific memory store.
#  * `onboarding`: Performs onboarding (identifying the project structure and essential tasks, e.g. for testing or building).
#  * `prepare_for_new_conversation`: Provides instructions for preparing for a new conversation (in order to continue with the necessary context).
#  * `read_file`: Reads a file within the project directory.
#  * `read_memory`: Reads the memory with the given name from Serena's project-specific memory store.
#  * `remove_project`: Removes a project from the Serena configuration.
#  * `replace_lines`: Replaces a range of lines within a file with new content.
#  * `replace_symbol_body`: Replaces the full definition of a symbol.
#  * `restart_language_server`: Restarts the language server, may be necessary when edits not through Serena happen.
#  * `search_for_pattern`: Performs a search for a pattern in the project.
#  * `summarize_changes`: Provides instructions for summarizing the changes made to the codebase.
#  * `switch_modes`: Activates modes by providing a list of their names
#  * `think_about_collected_information`: Thinking tool for pondering the completeness of collected information.
#  * `think_about_task_adherence`: Thinking tool for determining whether the agent is still on track with the current task.
#  * `think_about_whether_you_are_done`: Thinking tool for determining whether the task is truly completed.
#  * `write_memory`: Writes a named memory (for future reference) to Serena's project-specific memory store.
excluded_tools: []

# list of tools to include that would otherwise be disabled (particularly optional tools that are disabled by default)
included_optional_tools: []

# fixed set of tools to use as the base tool set (if non-empty), replacing Serena's default set of tools.
# This cannot be combined with non-empty excluded_tools or included_optional_tools.
fixed_tools: []

# list of mode names to that are always to be included in the set of active modes
# The full set of modes to be activated is base_modes + default_modes.
# If the setting is undefined, the base_modes from the global configuration (serena_config.yml) apply.
# Otherwise, this setting overrides the global configuration.
# Set this to [] to disable base modes for this project.
# Set this to a list of mode names to always include the respective modes for this project.
base_modes:
  - interactive
  - editing

# list of mode names that are to be activated by default.
# The full set of modes to be activated is base_modes + default_modes.
# If the setting is undefined, the default_modes from the global configuration (serena_config.yml) apply.
# Otherwise, this overrides the setting from the global configuration (serena_config.yml).
# This setting can, in turn, be overridden by CLI parameters (--mode).
default_modes:

# initial prompt for the project. It will always be given to the LLM upon activating the project
# (contrary to the memories, which are loaded on demand).
initial_prompt: |
  # AionUI Project Context

  AionUI is a unified AI agent graphical interface that transforms CLI AI tools into a modern chat interface.

  ## Tech Stack
  - **Desktop:** Electron 37.x (multi-process: main, renderer, workers)
  - **UI:** React 19.x + Arco Design 2.x + UnoCSS 0.66.x
  - **Language:** TypeScript 5.8.x (strict mode)
  - **Server:** Express 5.x (WebUI remote access)
  - **Database:** SQLite (better-sqlite3, offline-first)
  - **AI SDKs:** Anthropic, Google GenAI, OpenAI
  - **Build:** Webpack 6.x + Electron Forge 7.8.x + Electron Builder 26.x

  ## Architecture Patterns
  - Multi-process isolation: main process (DB, services), renderer (UI), workers (AI agents)
  - IPC via contextBridge in src/preload.ts (type-safe message system)
  - AI agents run in dedicated workers (gemini.ts, codex.ts, acp.ts) using node-pty
  - WebUI supports remote access with JWT auth and OIDC/SSO

  ## Key Conventions
  1. **UI Components:** Use Arco Design components (Button, Modal, Form, etc.)
  2. **IPC Communication:** Follow existing patterns in src/preload.ts
  3. **Strings:** All user-facing strings are hardcoded English (i18n removed in v1.8.2)
  4. **Native Modules:** better-sqlite3, node-pty, tree-sitter are webpack externals
  5. **Path Aliases:** Use @/* (src root), @renderer/*, @process/*, @worker/*
  6. **Error Handling:** Use structured error types, never silent failures
  7. **Testing:** Jest with ts-jest (tests/unit/, tests/integration/, tests/contract/)

  ## Critical Constraints
  - Never use direct require() for native modules in renderer — must be externals
  - Avoid circular imports between src/process/initStorage.ts and src/process/utils.ts
  - Docker builds require asar unpacking for native modules (see scripts/afterPack.js)
  - i18n was removed in v1.8.2 — all strings are hardcoded English, do not use t() or i18next

  ## Project Memories
  Detailed documentation is stored in .serena/memories/:
  - project-architecture.md — Multi-process architecture and services
  - branding-and-release-configuration.md — Branding customization guide
  - docker-packaging-constraints.md — Build system and native module handling
  - auth-system.md — Multi-user authentication and RBAC
  - code-patterns.md — IPC, worker, component, and database patterns
  - common-pitfalls.md — Known anti-patterns and gotchas
  - drift-integration.md — Drift Detect MCP tools, data boundaries, and workflows

  Consult these memories for detailed information on specific subsystems.

  ## AI Context Tools
  This project also uses **Drift Detect** (via `.mcp.json`) for pattern analysis,
  institutional memory (Cortex), call graph analysis, and data boundary enforcement.
  See drift-integration.md memory for details on when to use Drift vs Serena.
